defaults:
  - model: mid
  - data: sg2-ffhq

wandb_project: clip2latent
wandb_entity: null
name: null
device: "cuda:0"
resume: null
train:
  znorm_embed: false
  znorm_latent: true
  max_it: 1_000_000
  val_it: 10_000
  lr: 1.0e-4
  weight_decay: 1.0e-2
  ema_update_every: 10
  ema_beta: 0.9999
  ema_power: 0.75
