device: "cuda:0"
model:
  network:
    dim: 512
    num_timesteps: 1000
    depth: 6
    dim_head: 64
    heads: 8
  diffusion:
    image_embed_dim: 512
    timesteps: 1000
    cond_drop_prob: 0.2
    image_embed_scale: 1.0
    beta_schedule: "cosine"
    predict_x_start: True
data:
  bs: 32
  clip_feature_path: "data/sg2-ffhq-1024/clip_features.pt"
  latent_path: 'data/sg2-ffhq-1024/w_for_clip.pt'
  sg_pkl: 'https://api.ngc.nvidia.com/v2/models/nvidia/research/stylegan2/versions/1/files/stylegan2-ffhq-1024x1024.pkl'
  clip_variant: "ViT-B/32"
val:
  n_im_val_samples: 16
  text_val_samples: [
      "A photograph of a young man's with a beard",
      "A photograph of a old woman's face with grey hair",
      "A photograph of a child at a birthday party",
      "A picture of a face outside in bright sun in front of green grass",
      "This man has bangs arched eyebrows curly hair and a small nose",
      "A photo of Barack Obama",
      "An arctic explorer",
      "A clown's face covered in make up",
  ]
train:
  loop:
    print_it: 100
    max_it: 1000000
    val_it: 5000
    noise: false
  opt:
    lr: 3.0e-4
    weight_decay: 1.0e-2
    betas: [0.9, 0.999]